# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: futurodamemoria-afk/hugo-snds
  branch: main 

local_backend: true

media_folder: /static/media
public_folder: /media

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['date', 'title']
    sort: 'date:desc'
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Rascunho", name: "draft", widget: "boolean", default: true }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
